############################################################
# AWS Configuration
############################################################

aws_region = "ap-south-1"

instance_type = "t3.small"

ssh_username = "ec2-user"

############################################################
# Application Configuration
############################################################

application_name = "server-inventory"

############################################################
# AWS Secrets Manager
############################################################

secret_name = "server-inventory/nexus"

############################################################
# AMI Configuration
############################################################

ami_name_prefix = "backend-golden-ami"

environment = "dev"

owner = "Nasir"

############################################################
# NOTE
############################################################
#
# The following values are NOT stored here intentionally
# because they are generated by Terraform and passed
# automatically by the Jenkins pipeline during runtime.
#
# - subnet_id
# - security_group_id
# - iam_instance_profile
#
# Example:
#
# packer build \
#   -var "subnet_id=$(terraform output -raw packer_subnet_id)" \
#   -var "security_group_id=$(terraform output -raw packer_security_group_id)" \
#   -var "iam_instance_profile=$(terraform output -raw packer_instance_profile)" \
#   .
#
############################################################
